
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import java.awt.*;
import java.awt.event.*;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author junhyeok
 */
public class LoginForm extends javax.swing.JFrame {
    /**
     * Creates new form LoginForm
     */
    
    int loginResult = -1;
    
    public LoginForm() {
        this.addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void windowClosing(WindowEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void windowClosed(WindowEvent e) { // 로그인 창이 꺼진 뒤
                if(loginResult == -1) { // 로그인이 되지 않은 경우
                        System.exit(0); // 프로그램 종료
                } else { // 로그인 성공시
                    new JavaPOS().setVisible(true); // 메인 포스기 창 표시
                }
            }

            @Override
            public void windowIconified(WindowEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void windowDeiconified(WindowEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void windowActivated(WindowEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void windowDeactivated(WindowEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
            
        });
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        joinForm = new javax.swing.JDialog();
        lblJoinTitle = new javax.swing.JLabel();
        btnJoinAction = new javax.swing.JButton();
        btnJoinExit = new javax.swing.JButton();
        btnIDCheck = new javax.swing.JButton();
        lblJoinName = new javax.swing.JLabel();
        lblJoinID = new javax.swing.JLabel();
        lblJoinPWD = new javax.swing.JLabel();
        lblJoinPWDCheck = new javax.swing.JLabel();
        lblJoinEmail = new javax.swing.JLabel();
        txtJoinName = new javax.swing.JTextField();
        txtJoinID = new javax.swing.JTextField();
        txtJoinEmail = new javax.swing.JTextField();
        txtJoinPWD = new javax.swing.JPasswordField();
        txtJoinPWDCheck = new javax.swing.JPasswordField();
        lblTitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtPWD = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnJoinFormAction = new javax.swing.JButton();
        btnLoginExit = new javax.swing.JButton();

        lblJoinTitle.setText("회원 가입");

        btnJoinAction.setText("회원 가입");
        btnJoinAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJoinActionActionPerformed(evt);
            }
        });

        btnJoinExit.setText("취소");
        btnJoinExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJoinExitActionPerformed(evt);
            }
        });

        btnIDCheck.setText("중복 체크");
        btnIDCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIDCheckActionPerformed(evt);
            }
        });

        lblJoinName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJoinName.setText("이  름");

        lblJoinID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJoinID.setText("아이디");

        lblJoinPWD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJoinPWD.setText("비밀번호");

        lblJoinPWDCheck.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJoinPWDCheck.setText("비밀번호 확인");

        lblJoinEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJoinEmail.setText("이메일");

        javax.swing.GroupLayout joinFormLayout = new javax.swing.GroupLayout(joinForm.getContentPane());
        joinForm.getContentPane().setLayout(joinFormLayout);
        joinFormLayout.setHorizontalGroup(
            joinFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, joinFormLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblJoinTitle)
                .addGap(171, 171, 171))
            .addGroup(joinFormLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(joinFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, joinFormLayout.createSequentialGroup()
                        .addComponent(btnJoinExit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnJoinAction))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, joinFormLayout.createSequentialGroup()
                        .addComponent(lblJoinName, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtJoinName)
                        .addGap(110, 110, 110))
                    .addGroup(joinFormLayout.createSequentialGroup()
                        .addGroup(joinFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblJoinPWDCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblJoinID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblJoinPWD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblJoinEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(joinFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtJoinPWD, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtJoinID, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(txtJoinPWDCheck, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtJoinEmail))
                        .addGap(18, 18, 18)
                        .addComponent(btnIDCheck)))
                .addContainerGap())
        );
        joinFormLayout.setVerticalGroup(
            joinFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(joinFormLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblJoinTitle)
                .addGap(31, 31, 31)
                .addGroup(joinFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJoinName)
                    .addComponent(txtJoinName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(joinFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJoinID)
                    .addComponent(txtJoinID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIDCheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(joinFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJoinPWD)
                    .addComponent(txtJoinPWD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(joinFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJoinPWDCheck)
                    .addComponent(txtJoinPWDCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(joinFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJoinEmail)
                    .addComponent(txtJoinEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(joinFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnJoinAction)
                    .addComponent(btnJoinExit))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setText("로그인");

        jLabel2.setText("아이디");

        jLabel3.setText("비밀번호");

        btnLogin.setText("로그인");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnJoinFormAction.setText("회원가입");
        btnJoinFormAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJoinFormActionActionPerformed(evt);
            }
        });

        btnLoginExit.setText("종료");
        btnLoginExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(164, 164, 164)
                                .addComponent(lblTitle))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtID, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                                    .addComponent(txtPWD))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnJoinFormAction)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                        .addComponent(btnLoginExit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLogin)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPWD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin)
                    .addComponent(btnJoinFormAction)
                    .addComponent(btnLoginExit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // 로그인 버튼
        
        // ID, PWD 텍스트 필드에 값을 넣지 않은 경우
        if(txtID.getText().length() < 1 ||
           txtPWD.getText().length() < 1) {
           System.out.println("아이디, 비밀번호를 입력해 주십시오.");
           JOptionPane.showMessageDialog(null, "아이디, 비밀번호를 입력해 주십시오.", "로그인 실패", JOptionPane.ERROR_MESSAGE);
           return;
        }
        
        String userID = txtID.getText();
        String userPWD = txtPWD.getText();
        
        UserDAO userDAO = new UserDAO();
        int result = userDAO.login(userID, userPWD);
        if(result != 1) { // 로그인 실패일 경우
            System.out.println("로그인 실패");
            JOptionPane.showMessageDialog(null, "정보가 일치하지 않습니다.", "로그인 실패", JOptionPane.ERROR_MESSAGE);
        } else { // 로그인 성공일 경우
            JOptionPane.showMessageDialog(null, "환영합니다.", "로그인 성공", JOptionPane.INFORMATION_MESSAGE);
            System.out.println("로그인 성공");
            loginResult = 1;
            dispose();
        }
        
        
    }//GEN-LAST:event_btnLoginActionPerformed
    
    private void btnJoinFormActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJoinFormActionActionPerformed
        // 회원가입 창 표시
        joinForm.setLocation(350, 350);
        joinForm.setSize(400, 300);
        joinForm.show();
    }//GEN-LAST:event_btnJoinFormActionActionPerformed

    private void btnLoginExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginExitActionPerformed
        // 로그인 취소(프로그램 종료) 버튼
        dispose();
    }//GEN-LAST:event_btnLoginExitActionPerformed

    // 회원가입 -------------------------------------
    
    // 유저 키는 오라클 스퀸스 사용
    // CREATE SEQUENCE users_seq START WITH 1 INCREMENT BY 1 MAXVALUE 200 NOCYCLE NOCACHE;
    
    // -1일경우 중복 확인 안함, 0일경우 중복, 1일경우 사용 가능한 아이디
    int idCheck = -1;
    
    int nullCheck() { // 회원가입 프레임의 텍스트 필드 값이 입력되었는지 확인
        int result = 1;
        if (txtJoinName.getText().length() < 1 ||
            txtJoinID.getText().length() < 1 ||
            txtJoinPWD.getText().length() < 1 ||
            txtJoinPWDCheck.getText().length() < 1 ||
            txtJoinEmail.getText().length() < 1) {
   
            result = -1;
        }
        return result;
    }
    
    private void btnJoinActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJoinActionActionPerformed
        // 회원가입 버튼
        
        if(idCheck == -1) { // 중복체크를 하지 않은 경우
            System.out.println("중복체크 해 주십시오.");
            JOptionPane.showMessageDialog(null, "중복 확인 해 주십시오..", "회원가입 실패", JOptionPane.ERROR_MESSAGE);
        } else if(idCheck == 0) { // 아이디가 중복인 경우
            System.out.println("아이디 중복입니다.");
            JOptionPane.showMessageDialog(null, "아이디 중복입니다.", "회원가입 실패", JOptionPane.ERROR_MESSAGE);
        }
        
        int emptyCheck = nullCheck(); // 회원가입에 필요한 정보들을 모두 입력했는지 확인
        if(emptyCheck != 1) { // 정보를 입력하지 않은 경우
            System.out.println("빈칸을 채워주십시오.");
            JOptionPane.showMessageDialog(null, "빈칸을 채워주십시오.", "회원가입 실패", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String userName = txtJoinName.getText();
        String userID = txtJoinID.getText();
        String userPWD = txtJoinPWD.getText();
        String userPWDCheck = txtJoinPWDCheck.getText();
        String userEmail = txtJoinEmail.getText();
        
        // 유저 생성 날짜/시간
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        Date date = new Date();
        String userCreated = dateFormat.format(date);
        
        
        if(!userPWD.equals(userPWDCheck)) { // 비밀번호와 비밀번호 확인 텍스트 필드가 서로 일치하지 않은 경우
            System.out.println("비밀번호가 일치하지 않습니다.");
            JOptionPane.showMessageDialog(null, "비밀번호가 일치하지 않습니다.", "회원가입 실패", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(userEmail.length() < 1 || !userEmail.contains("@") || !userEmail.contains(".")) { // 입력한 이메일이 형식에 맞지 않을 경우
            System.out.println("이메일 형식에 맞게 입력해주십시오.");
            JOptionPane.showMessageDialog(null, "이메일을 형식에 맞게 입력해 주십시오..", "회원가입 실패", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        
        User user = new User(null, userName, userID, userPWD, userEmail, userCreated);
        UserDAO userDAO = new UserDAO();
        
        int result = userDAO.join(user);
        if(result != 1) { // 회원가입 실패인 경우
            System.out.println("회원가입 실패");
            JOptionPane.showMessageDialog(null, "회원가입 실패.", "회원가입 실패", JOptionPane.ERROR_MESSAGE);
        } else { // 회원가입 성공인 경우
            System.out.println("회원가입 성공");
            JOptionPane.showMessageDialog(null, "회원가입에 성공하였습니다.", "회원가입 성공", JOptionPane.INFORMATION_MESSAGE);
            txtClear();
            joinForm.dispose(); // 회원가입 창 종료
        }
        
    }//GEN-LAST:event_btnJoinActionActionPerformed

    private void btnJoinExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJoinExitActionPerformed
        // 회원가입 취소 버튼
        txtClear();
        joinForm.dispose(); // 회원가입 창 종료
    }//GEN-LAST:event_btnJoinExitActionPerformed

    private void txtClear() { // 회원가입 창의 텍스트필드들에 입력된 값들을 없앰
        txtJoinName.setText("");
        txtJoinID.setText("");
        txtJoinPWD.setText("");
        txtJoinPWDCheck.setText("");
        txtJoinEmail.setText("");
        
    }
    private void btnIDCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIDCheckActionPerformed
        // 회원가입 아이디 중복 체크 버튼
        
        if(txtJoinID.getText().length() < 1) {
            System.out.println("아이디를 입력해주십시오.");
            JOptionPane.showMessageDialog(null, "아이디를 입력해 주십시오.", "중복 확인 실패", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String userID = txtJoinID.getText();
        
        UserDAO userDAO = new UserDAO();
        int result = userDAO.idCheck(userID); // 아이디 중복 체크
        if(result != 1) { // 아이디가 중복일 경우(동일한 아이디가 DB에 이미 있는 경우)
            System.out.println("중복");
            JOptionPane.showMessageDialog(null, "아이디가 중복입니다.", "중복 확인 실패", JOptionPane.ERROR_MESSAGE);
            idCheck = 0; // idCheck 전역변수 0 (아이디 중복)
        } else { // 아이디 중복이 아닌 경우
            System.out.println("아이디 사용 가능");
            JOptionPane.showMessageDialog(null, "사용가능한 아이디입니다.", "중복 확인 성공", JOptionPane.INFORMATION_MESSAGE);
            idCheck = 1; // idCheck  전역변수 1 (사용 가능)
        }
    }//GEN-LAST:event_btnIDCheckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIDCheck;
    private javax.swing.JButton btnJoinAction;
    private javax.swing.JButton btnJoinExit;
    private javax.swing.JButton btnJoinFormAction;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLoginExit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JDialog joinForm;
    private javax.swing.JLabel lblJoinEmail;
    private javax.swing.JLabel lblJoinID;
    private javax.swing.JLabel lblJoinName;
    private javax.swing.JLabel lblJoinPWD;
    private javax.swing.JLabel lblJoinPWDCheck;
    private javax.swing.JLabel lblJoinTitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtJoinEmail;
    private javax.swing.JTextField txtJoinID;
    private javax.swing.JTextField txtJoinName;
    private javax.swing.JPasswordField txtJoinPWD;
    private javax.swing.JPasswordField txtJoinPWDCheck;
    private javax.swing.JPasswordField txtPWD;
    // End of variables declaration//GEN-END:variables
}
